- name: "breaking change"
  color: "ff0205"
  description: "This change will require a major version bump"
- name: "bug"
  color: "d73a4a"
  description: "Something isn't working"
- name: "dependencies"
  color: "0366d6"
  description: "Pull requests that update a dependency file"
- name: "documentation"
  color: "0075ca"
  description: "Improvements or additions to documentation"
- name: "duplicate"
  color: "cfd3d7"
  description: "This issue or pull request already exists"
- name: "environment"
  color: "703E17"
  description: "Improvement, to infra or build environment"
- name: "feature"
  color: "fbca04"
  description: "A new business feature"
- name: "in progress"
  color: "5ae1c2"
  description: "In flight work"
- name: "next release"
  color: "5319e7"
  description: "Completed work that is yet to be deployed"
- name: "technical debt"
  color: "c19337"
  description: "An issue describing some techinal debt that needs to be addressed in the future"
- name: "to do"
  color: "fbca04"
  description: "Work that is yet to be started"