name: Test and Deploy Library

env:
  VERSION_NUMBER: 0.0.1

on:
  push:
    branches:
    - master
    - develop
    - feature/*
    - release/*
    - hotfix/*
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Run tests
      run: dotnet test --logger "junit;LogFileName=results.xml"
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action/composite@v2
      if: ${{ github.actor != 'dependabot[bot]' }}
      with:
        files: "**/TestResults/*.xml"